var langSubstitute = {
    InFuture: "Sorry, you can't add an item in the future",
    BadUser: "Incorrect details, please retry",
    NonMatchingPassword: "Incorrect password, please try again",
    ServerError: "Sorry, could not complete this operation - please contact support",
    NoOfflineUser: "You must connect to the internet before attempting to login",
    Lockout2: "Incorrect details, you have 2 more chances before you will be locked out",
    Lockout1: "Incorrect details, you have 1 more chance before you will be locked out",
    LockoutOnline: "Incorrect details, you have now been locked out - an email has been sent to you with instructions for how to unlock your account",
    LockoutOffline: "Incorrect details, you have now been locked out - you must connect to the internet before attempting to login",
    SetPassword: "An email has been sent to you with instructions on how to set your password",
    ResetPassword: "An email has been sent to you with instructions on how to reset your password",
    BadEmail: "Sorry, this was unsuccessful. Please check the email address or contact Technical Support",
    ExpiredCode: "Sorry, reset code is incorrect or expired",
    Yes: "Yes",
    No: "No",
    WellDone48: "Well done, you have completed your 48hr intensive diary!",
    WellDoneEarnedBonus: "Well done, you have earned {0} gameplay bonus minutes!",
    NoActivityToday: "No Daily Activity recorded today, please update",
    NoActivityYesterday: "No Daily Activity recorded yesterday, please update",
    DoQuestionnaire: "Please fill out a questionnaire",
    Here: "here",
    ConnectFirst: "Please connect to the internet before contacting technical support",
    Offline: "You are currently offline",
    ActivityAdd: "ADD ACTIVITY  ",
    Update: "SAVE CHANGES  ",
    OfflineFunction: "<h1>Sorry this function is only available when you are connected to the internet.</h1><p>Please connect your device to the internet and then refresh this page.</p>",
    OfflineLink: "<h1>Sorry this function is only available when you are connected to the internet.</h1><p>Please connect your device to the internet and then retry the link.</p>",
    Genders: "Unknown,Male,Female,Not Specified",
    Titles: "Unknown,Mr,Master,Miss,Ms",
    Sizes: "small,medium,large",
    Severities: "mild,moderate,severe",
    WeePlaces: "toilet,underwear,on clothes,on floor,asleep,nappy,training pants",
    Months: "January,February,March,April,May,June,July,August,September,October,November,December",
    PreferredContacts: "Patient,Parent/Guardian",
    PleaseSelect: "Please Select",
    CheckInput: "Please check input in the red boxes",
    AgeBetween: "Age must be between {0} and {1}",
    CheckDoB: "Please check your Date of Birth",
    SelectRequired: "Please select all required items",
};

