using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Timesheet.Models
{
    public class Timesheet
    {
        public long id;             // when created (generated by the CLIENT)
        public DateTime when;
        public List<TimesheetEntry> entries;
    }
    public class TimesheetEntry
    {
        public long activityId;
        public int startMinutes;
        public int lengthMinutes;
    }
}